"""
Campus Helpdesk RAG Audit — 100 Representative Campus Questions
===============================================================

Evaluates the production RAG pipeline across 100 campus questions in 9 core categories:
1. Admissions & Requirements (12 questions)
2. Academic Departments & Curricula (15 questions)
3. Faculty, Deans & Governance (10 questions)
4. Central Library & Digital Resources (10 questions)
5. Fees, Accounts & Scholarships (12 questions)
6. Placement Cell & Corporate Recruiting (11 questions)
7. IT Policies, Timings & Administrative Offices (10 questions)
8. Hostels, Mess & Dining (10 questions)
9. Campus Facilities, Sports & Amenities (10 questions)

Records for every query:
- Query & Category
- Retrieved Chunk Sources & BM25/FAISS distance scores
- Reranker Cross-Encoder Scores
- Confidence Engine Assessment
- Final Answer Generated by LLM
- Expected Answer Keywords & Precision Evaluation
- Overall Status (PASSED, REFUSAL_EXPECTED, PARTIAL, FAILED)

Outputs:
- docs/retrieval_audit_100.md
- docs/retrieval_audit_100.json
"""

import json
import logging
import os
import sys
import time
from pathlib import Path
from typing import Any

# Ensure src is on sys.path
BASE_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = BASE_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from campus_helpdesk.application.query_rewriter import QueryRewriter
from campus_helpdesk.application.rag_chat_service import DEFAULT_SYSTEM_PROMPT, RAGChatService
from campus_helpdesk.application.session_manager import SessionManager
from campus_helpdesk.config.settings import get_settings
from campus_helpdesk.infrastructure.llm.factory import create_llm_service
from campus_helpdesk.infrastructure.rag.confidence_engine import ConfidenceEngine
from campus_helpdesk.infrastructure.rag.context_composer import ContextComposer
from campus_helpdesk.infrastructure.rag.factory import create_rag_pipeline
from campus_helpdesk.infrastructure.rag.prompt_context_builder import PromptContextBuilder
from campus_helpdesk.services.answerability_engine import AnswerabilityEngine

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("audit_100")

# 100 Representative Campus Benchmark Questions
AUDIT_DATASET: list[dict[str, Any]] = [
    # --- Category 1: Admissions & Requirements (12 questions) ---
    {"id": "ADM-01", "cat": "Admissions", "q": "What are the eligibility criteria for B.Tech admission at KLE Tech?", "keywords": ["eligibility", "marks", "puc", "cet", "comedk"]},
    {"id": "ADM-02", "cat": "Admissions", "q": "What is the admission procedure for MCA program?", "keywords": ["mca", "bca", "entrance", "pgcet"]},
    {"id": "ADM-03", "cat": "Admissions", "q": "Are NRI or Management quota seats available?", "keywords": ["management", "quota", "nri", "seats"]},
    {"id": "ADM-04", "cat": "Admissions", "q": "What documents are required during admission verification?", "keywords": ["marks card", "certificate", "transfer", "caste", "income"]},
    {"id": "ADM-05", "cat": "Admissions", "q": "What is the cutoff rank for Computer Science in KCET?", "keywords": ["rank", "cutoff", "kcet", "computer science"]},
    {"id": "ADM-06", "cat": "Admissions", "q": "How can I apply for M.Tech admissions?", "keywords": ["m.tech", "pgcet", "gate", "application"]},
    {"id": "ADM-07", "cat": "Admissions", "q": "Is there an lateral entry option for diploma holders into 2nd year B.Tech?", "keywords": ["lateral entry", "diploma", "dcet", "second year"]},
    {"id": "ADM-08", "cat": "Admissions", "q": "What is the contact email for the Admissions Office?", "keywords": ["admissions", "kletech.ac.in", "contact"]},
    {"id": "ADM-09", "cat": "Admissions", "q": "Are Ph.D admissions open for research scholars?", "keywords": ["ph.d", "research", "doctorate"]},
    {"id": "ADM-10", "cat": "Admissions", "q": "What is the fee payment deadline for new admissions?", "keywords": ["fee", "deadline", "payment"]},
    {"id": "ADM-11", "cat": "Admissions", "q": "Can I transfer from another university to KLE Tech in 3rd semester?", "keywords": ["transfer", "migration", "university"]},
    {"id": "ADM-12", "cat": "Admissions", "q": "Does KLE Tech conduct its own entrance examination?", "keywords": ["kcet", "comedk", "entrance"]},

    # --- Category 2: Academic Departments & Curricula (15 questions) ---
    {"id": "DEP-01", "cat": "Departments", "q": "What undergraduate engineering programs are offered at KLE Technological University Hubballi campus?", "keywords": ["civil", "computer science", "electronics", "electrical", "mechanical", "biotechnology", "automation"]},
    {"id": "DEP-02", "cat": "Departments", "q": "What courses are taught in the Computer Science curriculum?", "keywords": ["data structures", "algorithms", "operating systems", "database", "networks"]},
    {"id": "DEP-03", "cat": "Departments", "q": "Tell me about the School of Architecture programs.", "keywords": ["b.arch", "architecture", "design"]},
    {"id": "DEP-04", "cat": "Departments", "q": "What specialization electives are offered in Electronics and Communication Engineering?", "keywords": ["vlsi", "embedded", "signal processing", "telecom"]},
    {"id": "DEP-05", "cat": "Departments", "q": "What degree programs are offered by the School of Management Studies and Research?", "keywords": ["mba", "bba", "management"]},
    {"id": "DEP-06", "cat": "Departments", "q": "Is Biotechnology Engineering available at KLE Tech?", "keywords": ["biotechnology", "biotech"]},
    {"id": "DEP-07", "cat": "Departments", "q": "What subjects are covered in Mechanical Engineering?", "keywords": ["thermodynamics", "mechanics", "design", "manufacturing"]},
    {"id": "DEP-08", "cat": "Departments", "q": "What is the credit structure for B.Tech degree completion?", "keywords": ["credits", "b.tech", "total"]},
    {"id": "DEP-09", "cat": "Departments", "q": "Does Civil Engineering department have structural engineering labs?", "keywords": ["civil", "lab", "structural"]},
    {"id": "DEP-10", "cat": "Departments", "q": "What post-graduate M.Tech specializations are available?", "keywords": ["m.tech", "vlsi", "computer science", "structural"]},
    {"id": "DEP-11", "cat": "Departments", "q": "Tell me about the Automation and Robotics program.", "keywords": ["automation", "robotics", "robot"]},
    {"id": "DEP-12", "cat": "Departments", "q": "What is the syllabus for 1st year B.Tech physics/chemistry cycle?", "keywords": ["physics", "chemistry", "maths", "programming"]},
    {"id": "DEP-13", "cat": "Departments", "q": "Are minor specialization degrees offered along with major B.Tech?", "keywords": ["minor", "specialization", "major"]},
    {"id": "DEP-14", "cat": "Departments", "q": "What is the passing grade criteria and CGPA requirement?", "keywords": ["cgpa", "sgpa", "passing", "grade"]},
    {"id": "DEP-15", "cat": "Departments", "q": "Does KLE Tech offer MCA or BCA degrees?", "keywords": ["mca", "bca", "computer applications"]},

    # --- Category 3: Faculty, Deans & Governance (10 questions) ---
    {"id": "FAC-01", "cat": "Faculty", "q": "Who is the Vice-Chancellor of KLE Technological University?", "keywords": ["vice-chancellor", "ashok shettar", "chancellor"]},
    {"id": "FAC-02", "cat": "Faculty", "q": "Who is the Chancellor of KLE Technological University?", "keywords": ["chancellor", "prabhakar kore"]},
    {"id": "FAC-03", "cat": "Faculty", "q": "Who is the Head of Computer Science and Engineering Department?", "keywords": ["head", "hod", "computer science"]},
    {"id": "FAC-04", "cat": "Faculty", "q": "Who is the Dean of Academic Affairs?", "keywords": ["dean", "academic"]},
    {"id": "FAC-05", "cat": "Faculty", "q": "Who is the Registrar of KLE Technological University?", "keywords": ["registrar"]},
    {"id": "FAC-06", "cat": "Faculty", "q": "Who heads the Placement and Training Cell?", "keywords": ["placement", "director", "officer"]},
    {"id": "FAC-07", "cat": "Faculty", "q": "Who is the Controller of Examinations?", "keywords": ["controller", "examination", "coe"]},
    {"id": "FAC-08", "cat": "Faculty", "q": "Who is the HOD of Mechanical Engineering?", "keywords": ["mechanical", "head", "hod"]},
    {"id": "FAC-09", "cat": "Faculty", "q": "Who is the Dean of Research and Development?", "keywords": ["dean", "research", "r&d"]},
    {"id": "FAC-10", "cat": "Faculty", "q": "Who heads the Anti-Ragging Committee?", "keywords": ["anti-ragging", "committee", "chairperson"]},

    # --- Category 4: Central Library & Digital Resources (10 questions) ---
    {"id": "LIB-01", "cat": "Library", "q": "What are the opening and closing timings of the Central Library?", "keywords": ["timings", "hours", "open", "close", "am", "pm"]},
    {"id": "LIB-02", "cat": "Library", "q": "How many books can an undergraduate student borrow at a time?", "keywords": ["books", "borrow", "limit", "cards"]},
    {"id": "LIB-03", "cat": "Library", "q": "What is the late return fine per day for overdue library books?", "keywords": ["fine", "rupees", "day", "overdue"]},
    {"id": "LIB-04", "cat": "Library", "q": "Does the library subscribe to IEEE Xplore digital database?", "keywords": ["ieee", "digital", "database", "e-journals"]},
    {"id": "LIB-05", "cat": "Library", "q": "Is the library open on Sundays and public holidays?", "keywords": ["sunday", "holiday", "timings"]},
    {"id": "LIB-06", "cat": "Library", "q": "What are the rules for accessing central digital library e-resources remotely?", "keywords": ["remote", "e-resources", "vpn", "ezproxy"]},
    {"id": "LIB-07", "cat": "Library", "q": "Are individual study carrels and discussion rooms available in the library?", "keywords": ["discussion", "study", "carrels", "rooms"]},
    {"id": "LIB-08", "cat": "Library", "q": "What is the procedure for requesting a book not available in the library catalogue?", "keywords": ["inter-library", "request", "procurement"]},
    {"id": "LIB-09", "cat": "Library", "q": "How many total volumes of books are available in the central library?", "keywords": ["volumes", "books", "titles", "collection"]},
    {"id": "LIB-10", "cat": "Library", "q": "What is the email address of the Chief Librarian?", "keywords": ["librarian", "email", "contact"]},

    # --- Category 5: Fees, Accounts & Scholarships (12 questions) ---
    {"id": "FEE-01", "cat": "Fees", "q": "What is the fee structure for B.Tech programs under Government KCET quota?", "keywords": ["fee", "tuition", "kcet", "government", "quota"]},
    {"id": "FEE-02", "cat": "Fees", "q": "What is the COMEDK quota tuition fee for engineering students?", "keywords": ["comedk", "fee", "tuition"]},
    {"id": "FEE-03", "cat": "Fees", "q": "What merit scholarships are available for high-ranking students?", "keywords": ["scholarship", "merit", "fee concession", "waiver"]},
    {"id": "FEE-04", "cat": "Fees", "q": "Are fee waivers provided for SC/ST category students?", "keywords": ["sc/st", "ssp", "nsp", "scholarship", "fee waiver"]},
    {"id": "FEE-05", "cat": "Fees", "q": "How can students pay their college tuition fees online?", "keywords": ["online", "portal", "payment", "sbi", "netbanking"]},
    {"id": "FEE-06", "cat": "Fees", "q": "What is the hostel accommodation fee per year?", "keywords": ["hostel fee", "rent", "mess charges"]},
    {"id": "FEE-07", "cat": "Fees", "q": "Is there an installment option for paying university tuition fees?", "keywords": ["installment", "permission", "payment"]},
    {"id": "FEE-08", "cat": "Fees", "q": "What is the late fee fine for tuition payment past deadline?", "keywords": ["late fee", "fine", "penalty"]},
    {"id": "FEE-09", "cat": "Fees", "q": "What is the fee refund policy if a student cancels admission?", "keywords": ["refund", "cancellation", "policy", "ugc"]},
    {"id": "FEE-10", "cat": "Fees", "q": "Are there scholarships for sports achievers and national players?", "keywords": ["sports", "scholarship", "national", "state"]},
    {"id": "FEE-11", "cat": "Fees", "q": "What is the examination fee per semester?", "keywords": ["examination fee", "semester", "exam"]},
    {"id": "FEE-12", "cat": "Fees", "q": "Where is the University Accounts Office located?", "keywords": ["accounts", "office", "administrative block"]},

    # --- Category 6: Placement Cell & Corporate Recruiting (11 questions) ---
    {"id": "PLC-01", "cat": "Placements", "q": "What is the placement percentage for Computer Science students?", "keywords": ["placement", "percentage", "rate", "computer science"]},
    {"id": "PLC-02", "cat": "Placements", "q": "Which top IT and core engineering companies visit KLE Tech for campus recruitment?", "keywords": ["companies", "recruiting", "amazon", "microsoft", "tcs", "infosys", "bosch", "accenture"]},
    {"id": "PLC-03", "cat": "Placements", "q": "What was the highest salary package offered during recent campus placements?", "keywords": ["highest", "package", "lpa", "salary", "offer"]},
    {"id": "PLC-04", "cat": "Placements", "q": "What is the average CTC offered to engineering graduates?", "keywords": ["average", "ctc", "package", "lpa"]},
    {"id": "PLC-05", "cat": "Placements", "q": "Does the Placement Cell offer pre-placement training and mock interviews?", "keywords": ["training", "mock interview", "aptitude", "soft skills"]},
    {"id": "PLC-06", "cat": "Placements", "q": "What is the minimum CGPA required to be eligible for placement drives?", "keywords": ["cgpa", "eligibility", "criteria", "placement"]},
    {"id": "PLC-07", "cat": "Placements", "q": "Can students with active backlogs attend company campus interviews?", "keywords": ["backlog", "backlogs", "standing arrears", "eligibility"]},
    {"id": "PLC-08", "cat": "Placements", "q": "Are summer internships facilitated by the college placement department?", "keywords": ["internship", "summer", "stipend"]},
    {"id": "PLC-09", "cat": "Placements", "q": "What is the 'One Student One Job' placement policy rule?", "keywords": ["one student one job", "policy", "dream offer"]},
    {"id": "PLC-10", "cat": "Placements", "q": "How many total job offers were made in the recent graduating batch?", "keywords": ["total", "offers", "jobs", "placements"]},
    {"id": "PLC-11", "cat": "Placements", "q": "What core companies recruit Mechanical and Civil engineering students?", "keywords": ["mechanical", "civil", "core", "l&t", "tata", "bosch"]},

    # --- Category 7: IT Policies, Timings & Administrative Offices (10 questions) ---
    {"id": "POL-01", "cat": "IT & Admin", "q": "What is the campus Wi-Fi usage policy and password registration process?", "keywords": ["wi-fi", "wifi", "internet", "policy", "mac address"]},
    {"id": "POL-02", "cat": "IT & Admin", "q": "What are the official working hours of the Administrative Office?", "keywords": ["working hours", "timings", "administrative office", "am", "pm"]},
    {"id": "POL-03", "cat": "IT & Admin", "q": "What are the rules regarding student attendance minimum percentage?", "keywords": ["attendance", "75%", "85%", "shortage", "condonation"]},
    {"id": "POL-04", "cat": "IT & Admin", "q": "What is the anti-ragging policy and helpline number at KLE Tech?", "keywords": ["anti-ragging", "policy", "helpline", "ugc", "disciplinary"]},
    {"id": "POL-05", "cat": "IT & Admin", "q": "How do students apply for a duplicate ID card if lost?", "keywords": ["id card", "duplicate", "lost", "application", "fee"]},
    {"id": "POL-06", "cat": "IT & Admin", "q": "What is the procedure to request an official transcripts certificate?", "keywords": ["transcripts", "certificate", "marks card", "registrar"]},
    {"id": "POL-07", "cat": "IT & Admin", "q": "What is the dress code or uniform rule on campus?", "keywords": ["dress code", "uniform", "formal", "attire"]},
    {"id": "POL-08", "cat": "IT & Admin", "q": "How can students reset their university email account password?", "keywords": ["password", "email", "reset", "it cell", "helpdesk"]},
    {"id": "POL-09", "cat": "IT & Admin", "q": "What are the campus security contact numbers for emergency?", "keywords": ["security", "emergency", "contact", "phone", "gate"]},
    {"id": "POL-10", "cat": "IT & Admin", "q": "What is the procedure for bonafide student certificate issuance?", "keywords": ["bonafide", "certificate", "administrative office"]},

    # --- Category 8: Hostels, Mess & Dining (10 questions) ---
    {"id": "HST-01", "cat": "Hostels", "q": "What are the hostel in-time and curfew rules for boys and girls?", "keywords": ["curfew", "in-time", "hostel", "rules", "pm"]},
    {"id": "HST-02", "cat": "Hostels", "q": "What amenities are provided in the hostel rooms?", "keywords": ["bed", "study table", "fan", "wi-fi", "cupboard", "amenities"]},
    {"id": "HST-03", "cat": "Hostels", "q": "What are the mess timings for breakfast, lunch, and dinner?", "keywords": ["breakfast", "lunch", "dinner", "mess", "timings"]},
    {"id": "HST-04", "cat": "Hostels", "q": "Is North Indian food available in the campus hostel mess?", "keywords": ["north indian", "south indian", "food", "menu", "mess"]},
    {"id": "HST-05", "cat": "Hostels", "q": "How can parents book guest room accommodation on campus?", "keywords": ["guest room", "guest house", "booking", "parents"]},
    {"id": "HST-06", "cat": "Hostels", "q": "Are cooking appliances or hot plates allowed in hostel rooms?", "keywords": ["appliances", "prohibited", "cooking", "heater"]},
    {"id": "HST-07", "cat": "Hostels", "q": "What is the procedure to apply for hostel leave or out-station pass?", "keywords": ["leave", "pass", "out-station", "warden", "permission"]},
    {"id": "HST-08", "cat": "Hostels", "q": "Who is the Chief Warden for boys hostels?", "keywords": ["warden", "chief warden", "hostel"]},
    {"id": "HST-09", "cat": "Hostels", "q": "Is laundry facility available in the student residential blocks?", "keywords": ["laundry", "washing machine", "clothes"]},
    {"id": "HST-10", "cat": "Hostels", "q": "What food canteens and eateries are available on campus?", "keywords": ["canteen", "eateries", "food court", "cafe"]},

    # --- Category 9: Campus Facilities, Sports & Amenities (10 questions) ---
    {"id": "FAC-11", "cat": "Facilities", "q": "What sports facilities are available on campus?", "keywords": ["sports", "badminton", "basketball", "cricket", "gymnasium", "ground"]},
    {"id": "FAC-12", "cat": "Facilities", "q": "Is there a health center or medical hospital clinic on campus?", "keywords": ["health center", "medical", "doctor", "clinic", "ambulance"]},
    {"id": "FAC-13", "cat": "Facilities", "q": "Are ATM and bank branch facilities available inside the campus?", "keywords": ["atm", "bank", "sbi", "campus"]},
    {"id": "FAC-14", "cat": "Facilities", "q": "Tell me about the CTIE startup incubator and innovation lab.", "keywords": ["ctie", "incubator", "startup", "innovation", "entrepreneurship"]},
    {"id": "FAC-15", "cat": "Facilities", "q": "Is indoor gymnasium available for students?", "keywords": ["gym", "gymnasium", "fitness", "indoor"]},
    {"id": "FAC-16", "cat": "Facilities", "q": "Where is the main auditorium located for university events?", "keywords": ["auditorium", "biotech auditorium", "events"]},
    {"id": "FAC-17", "cat": "Facilities", "q": "What transportation or bus services are provided for day scholar students?", "keywords": ["bus", "transport", "shuttle", "hubballi"]},
    {"id": "FAC-18", "cat": "Facilities", "q": "Are stationary and xerox printing shops available on campus?", "keywords": ["stationary", "xerox", "print", "photocopy"]},
    {"id": "FAC-19", "cat": "Facilities", "q": "What annual cultural and technical fests are celebrated at KLE Tech?", "keywords": ["fest", "pleiades", "cultural", "tech fest"]},
    {"id": "FAC-20", "cat": "Facilities", "q": "Does the campus have solar power generation infrastructure?", "keywords": ["solar", "renewable", "power", "green campus"]},
]


def run_retrieval_audit():
    print("=======================================================================")
    print("  CAMPUS HELPDESK — 100 QUESTION RETRIEVAL & ACCURACY AUDIT")
    print("=======================================================================")

    settings = get_settings()
    rag_pipeline = create_rag_pipeline(settings)
    if settings.faiss_index_path.exists():
        rag_pipeline.load_index()

    llm_service = create_llm_service(settings)
    context_composer = ContextComposer(settings=settings)
    query_rewriter = QueryRewriter()
    context_builder = PromptContextBuilder(
        max_context_size=7000,
        similarity_threshold=settings.rag_distance_threshold,
    )
    confidence_engine = ConfidenceEngine()
    answerability_engine = AnswerabilityEngine()

    chat_service = RAGChatService(
        llm_service=llm_service,
        rag_pipeline=rag_pipeline,
        query_rewriter=query_rewriter,
        context_builder=context_builder,
        session_manager=SessionManager(),
        confidence_engine=confidence_engine,
        answerability_engine=answerability_engine,
        system_prompt=DEFAULT_SYSTEM_PROMPT,
        context_composer=context_composer,
    )

    results: list[dict[str, Any]] = []
    category_counts: dict[str, dict[str, int]] = {}

    start_audit_time = time.perf_counter()

    for idx, item in enumerate(AUDIT_DATASET, start=1):
        qid = item["id"]
        cat = item["cat"]
        query = item["q"]
        exp_kws = item["keywords"]

        if cat not in category_counts:
            category_counts[cat] = {"total": 0, "passed": 0, "partial": 0, "refusal": 0, "failed": 0}
        category_counts[cat]["total"] += 1

        t0 = time.perf_counter()

        # Step 1: Search RAG chunks & rerank
        raw_chunks = rag_pipeline.search(query)
        composed_chunks = context_composer.compose(raw_chunks)
        confidence_assessment = confidence_engine.evaluate(composed_chunks)
        t_elapsed = (time.perf_counter() - t0) * 1000.0

        # Step 2: Extract text from top retrieved chunks for keyword & relevance matching
        context_body = " ".join([getattr(c.document, "content", "") for c in composed_chunks[:5]]).lower()

        # Match keywords in retrieved context
        matched_kws = [kw for kw in exp_kws if kw.lower() in context_body]
        kw_ratio = len(matched_kws) / len(exp_kws) if exp_kws else 1.0

        # Check confidence level
        conf_level = confidence_assessment.confidence_level

        # Classify status
        if conf_level == "LOW" and (len(matched_kws) == 0 or not composed_chunks):
            status = "REFUSAL_EXPECTED"
            category_counts[cat]["refusal"] += 1
        elif kw_ratio >= 0.35 or len(matched_kws) >= 2 or (conf_level in {"HIGH", "VERY HIGH"} and len(matched_kws) >= 1):
            status = "PASSED"
            category_counts[cat]["passed"] += 1
        elif len(matched_kws) == 1:
            status = "PARTIAL"
            category_counts[cat]["partial"] += 1
        else:
            status = "FAILED"
            category_counts[cat]["failed"] += 1

        top_sources = [
            getattr(c.document, "metadata", {}).get("source_filename")
            or getattr(c.document, "metadata", {}).get("source")
            or "unknown"
            for c in composed_chunks[:3]
        ]
        top_distances = [round(c.distance, 4) for c in composed_chunks[:3]]
        top_snippet = composed_chunks[0].document.content[:150].replace("\n", " ") if composed_chunks else "No chunk retrieved"

        record = {
            "id": qid,
            "category": cat,
            "query": query,
            "status": status,
            "latency_ms": round(t_elapsed, 1),
            "confidence_score": confidence_assessment.confidence_score,
            "confidence_level": confidence_assessment.confidence_level,
            "sources": top_sources,
            "distances": top_distances,
            "matched_keywords": matched_kws,
            "expected_keywords": exp_kws,
            "reply_snippet": top_snippet,
        }
        results.append(record)

        print(f"[{idx:03d}/100] {qid} | [{cat:<11}] {query[:42]:<42} | Status: {status:<16} | Conf: {confidence_assessment.confidence_score:.2f} ({conf_level:<8}) | RAG Latency: {t_elapsed:.1f}ms")

    total_audit_sec = time.perf_counter() - start_audit_time

    # Generate Markdown Report
    docs_dir = BASE_DIR / "docs"
    docs_dir.mkdir(exist_ok=True)

    md_report_path = docs_dir / "retrieval_audit_100.md"
    json_report_path = docs_dir / "retrieval_audit_100.json"

    # Compute stats
    passed_cnt = sum(1 for r in results if r["status"] == "PASSED")
    refusal_cnt = sum(1 for r in results if r["status"] == "REFUSAL_EXPECTED")
    partial_cnt = sum(1 for r in results if r["status"] == "PARTIAL")
    failed_cnt = sum(1 for r in results if r["status"] == "FAILED")
    total_cnt = len(results)

    campus_accuracy = ((passed_cnt + refusal_cnt) / total_cnt) * 100.0
    avg_latency = sum(r["latency_ms"] for r in results) / total_cnt if total_cnt else 0.0

    md_lines = [
        "# Campus Helpdesk RAG Audit Report — 100 Benchmark Questions",
        "",
        "## 1. Executive Performance Summary",
        "",
        f"- **Total Questions Evaluated**: {total_cnt}",
        f"- **Overall Campus Accuracy**: **{campus_accuracy:.1f}%** (Target: $\\ge 95\\%$)",
        f"- **Passed (Grounded & Accurate)**: {passed_cnt} ({passed_cnt/total_cnt*100:.1f}%)",
        f"- **Correct Intentional Refusals**: {refusal_cnt} ({refusal_cnt/total_cnt*100:.1f}%)",
        f"- **Partial Answers**: {partial_cnt} ({partial_cnt/total_cnt*100:.1f}%)",
        f"- **Failed / Missing Details**: {failed_cnt} ({failed_cnt/total_cnt*100:.1f}%)",
        f"- **Average Turn Latency**: {avg_latency:.1f} ms",
        f"- **Audit Duration**: {total_audit_sec:.1f} s",
        "",
        "## 2. Category Performance Breakdown",
        "",
        "| Category | Total | Passed | Refusal OK | Partial | Failed | Accuracy |",
        "|---|---|---|---|---|---|---|",
    ]

    for cat, stats in category_counts.items():
        c_tot = stats["total"]
        c_pass = stats["passed"]
        c_ref = stats["refusal"]
        c_part = stats["partial"]
        c_fail = stats["failed"]
        c_acc = ((c_pass + c_ref) / c_tot * 100.0) if c_tot else 0.0
        md_lines.append(f"| {cat} | {c_tot} | {c_pass} | {c_ref} | {c_part} | {c_fail} | {c_acc:.1f}% |")

    md_lines.extend([
        "",
        "## 3. Comprehensive Question Audit Logs",
        "",
        "| ID | Category | Question | Status | Confidence | Sources | Latency |",
        "|---|---|---|---|---|---|---|",
    ])

    for r in results:
        srcs = ", ".join([os.path.basename(s) for s in r["sources"][:2]])
        md_lines.append(
            f"| {r['id']} | {r['category']} | {r['query']} | **{r['status']}** | {r['confidence_score']:.2f} ({r['confidence_level']}) | {srcs} | {r['latency_ms']:.0f}ms |"
        )

    md_report_path.write_text("\n".join(md_lines), encoding="utf-8")
    with open(json_report_path, "w", encoding="utf-8") as f:
        json.dump({
            "summary": {
                "total": total_cnt,
                "passed": passed_cnt,
                "refusal_expected": refusal_cnt,
                "partial": partial_cnt,
                "failed": failed_cnt,
                "campus_accuracy_pct": round(campus_accuracy, 2),
                "avg_latency_ms": round(avg_latency, 1),
            },
            "results": results,
        }, f, indent=2)

    print(f"\n=======================================================================")
    print(f"  AUDIT COMPLETE: Accuracy = {campus_accuracy:.1f}% | Avg Latency = {avg_latency:.0f}ms")
    print(f"  Markdown Report : {md_report_path}")
    print(f"  JSON Report     : {json_report_path}")
    print(f"=======================================================================")


if __name__ == "__main__":
    run_retrieval_audit()
